version: '3.8'
name: ms-video-processing
services:
  video-processing-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-processing-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8086
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: /app/videos/uploads
      STORAGE_OUTPUT_PATH: /app/videos/processed
      RABBITMQ_HOST: host.docker.internal
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: fiapx
      RABBITMQ_USER: fiapx
      RABBITMQ_PASSWORD: fiapx123
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-api:8090}
      FFMPEG_TIMEOUT_MINUTES: 10
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_APP_NAME: video-processing-ms-local
    ports:
      - "8086:8086"
    volumes:
      - .\videos:/app/videos
    networks:
      - app-network
      - fiap-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  fiap-network:
    external: true
    name: fiap-network

