apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-api
  namespace: fiapx
  labels:
    app: video-processing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processing-api
  template:
    metadata:
      labels:
        app: video-processing-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8086"
        prometheus.io/scheme: "http"
    spec:
      containers:
        - name: video-processing-api
          image: video-processing-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              name: http
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SWAGGER_SERVER_URL
              value: "/processing"
            - name: STORAGE_TYPE
              value: local
            - name: STORAGE_LOCAL_PATH
              value: /app/videos/uploads
            - name: STORAGE_OUTPUT_PATH
              value: /app/videos/processed
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: AUTH_SERVICE_URL
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_VHOST
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
          volumeMounts:
            - name: video-storage
              mountPath: /app/videos

          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: fiapx-video-pvc
